import React from "react";
import { Link } from "react-router-dom";
const Hoteal=()=>{
return<>
<div className="hotelcontainer">
    <div className="card1"><div className="cardimg2"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card2"><div className="cardimg3"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card3"><div className="cardimg4"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card4"><div className="cardimg5"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card5"><div className="cardimg6"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card6"><div className="cardimg7"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card7"><div className="cardimg8"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card8"><div className="cardimg9"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card9"><div className="cardimg10"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card10"><div className="cardimg11"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card11"><div className="cardimg12"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>
    <div className="card11"><div className="cardimg12"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?</div><Link to="/Contact_us"><button type="submit" className="contact_us">Contact us</button></Link></div>

</div>
</>
};
export default Hoteal;