import React from "react";
import { Link } from "react-router-dom";

const Services=()=>{
return<>
<div className="hotelcontainer">
    <div className="scard"><div className="scardimg1" ></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima odit perferendis provident sequi cupiditate praesentium, magni beatae quisquam error ratione perspiciatis officiis velit eos non? Harum dolorem aperiam velit id.</div><Link to='/Hotel'><button type="submit" className="contact_us2">CHECK HOTELS</button></Link></div>
    <div className="scard1"><div className="scardimg2"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta iste nemo maxime suscipit veniam officiis accusantium, inventore, quasi tempore nam eligendi. Molestias consequatur fuga quo tenetur itaque reiciendis, eius earum?</div><Link to='/Hotel'><button type="submit" className="contact_us2">CHECK HOTELS</button></Link></div><br />
    <div className="scard2"><div className="scardimg3"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem magnam itaque, obcaecati fugiat sit provident. In dolore dolorum culpa molestiae veniam tenetur fugiat ipsa, dolorem, labore laudantium tempore magnam consectetur?</div><Link to='/Hotel'><button type="submit" className="contact_us2">CHECK HOTELS</button></Link></div>
    <div className="scard3"><div className="scardimg4"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?Lorem ipsum dolor sit amet consectetur adipisicing elit. At, vitae magnam suscipit omnis animi atque provident veniam! Dolores laboriosam consequatur sit necessitatibus voluptatibus amet numquam, quas rem quibusdam similique recusandae?</div><Link to='/Hotel'><button type="submit" className="contact_us2">CHECK HOTELS</button></Link></div><br />
    <div className="scard4"><div className="scardimg5"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident nisi animi nam a iusto voluptates nihil, repellendus dolorem blanditiis placeat eum! Vel asperiores modi veritatis qui cumque, sed aliquam nesciunt.</div><Link to='/Hotel'><button type="submit" className="contact_us2">CHECK HOTELS</button></Link></div>
    <div className="scard5"><div className="scardimg6"></div><div className="h_name">NIRVANA</div> <div className="dis">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, dolore tenetur nemo odit optio dolores explicabo, eos laudantium error ratione rem nisi culpa laborum sequi quae at vitae nesciunt minus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti, voluptate quod quia fugiat praesentium rerum cupiditate, tempore cum atque quisquam nobis. Fuga odit earum eligendi autem corporis nulla ut alias.</div><Link to='/Hotel'><button type="submit" className="contact_us2">CHECK HOTELS</button></Link></div>
    </div>
</>
};
export default Services;